import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import styles from '@/app/page.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className={styles.navigationContainer}>
          <div className={styles.logo}>
            <Link href="/">Home</Link>
          </div>
          <div className={styles.menu}>menu</div>
        </nav>
        <main className={styles.main}>
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
}
